.TH JACKREC "1" "June 2002" "0.91.1"
.SH NAME
jackrec \- The JACK Audio Connection Kit example client
.SH SYNOPSYS
.B jackrec
-f filename [ -d second ] [ -b bitdepth ] port1 [ port2 ... ]
.SH DESCRIPTION
.B jackrec
is an example client for the JACK Audio Connection Kit.
.SH AUTHORS
Paul Davis and others.
.PP
This manpage was written by Stefan Schwandter <e9925373@student.tuwien.ac.at>

