.TH JACK_BUFSIZE "1" "December 2003" "0.91.1"
.SH NAME
jack_bufsize \- The JACK Audio Connection Kit example client
.SH SYNOPSYS
.B jack_bufsize bufsize
.SH DESCRIPTION
.B jack_bufsize
jack_bufsize sets the size of the buffer (frames per period) used in JACK. 
This change happens on-line (jackd and its clients do not need to be 
restarted).
.SH AUTHOR
Paul Davis
.PP
This manpage was written by Robert Jordens <jordens@debian.org> for Debian.

