.TH JACK_CONNECT "1" "June 2002" "0.91.1"
.SH NAME
jack_connect \- The JACK Audio Connection Kit example client
.SH SYNOPSYS
.B jack_connect
src_port dst_port
.PP
The source port must be an output port of the source client.
The destination port must be an input port of the destination client.
.SH DESCRIPTION
.B jack_connect
is an example client for the JACK Audio Connection Kit.
.SH AUTHOR
Jeremy Hall
.PP
This manpage was written by Stefan Schwandter <e9925373@student.tuwien.ac.at>

