.TH JACK_TRANSPORT "1" "August 2003" "0.91.1"
.SH NAME
jack_transport \- The JACK Audio Connection Kit example client
.SH SYNOPSYS
.B jack_transport
.SH DESCRIPTION
.B jack_transport
is an example client for the JACK Audio Connection Kit. It supports
controlling the JACK transport system. Type help at jack_transport's
command prompt to see the available commands.
.SH AUTHOR
Jeremy Hall
.PP
This manpage was written by Robert Jordens <jordens@debian.org> for Debian.

