.TH JACK_DISCONNECT "1" "June 2002" "0.91.1"
.SH NAME
jack_disconnect \- The JACK Audio Connection Kit example client
.SH SYNOPSYS
.B jack_disconnect
src_port dst_port
.PP
The source port must be an output port of the source client.
The destination port must be an input port of the destination client.
.SH DESCRIPTION
.B jack_disconnect
is an example client for the JACK Audio Connection Kit.
.SH AUTHORS
Paul Davis and others.
.PP
This manpage was written by Stefan Schwandter <e9925373@student.tuwien.ac.at>

