name: Source Code tarball

on:
  push:

jobs:
  archive_source_code:
    name: Create source code tarball
    runs-on: ubuntu-18.04
    env:
      ARCHIVE_BASENAME: jack1-${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Archive source code
        shell: bash
        run: |
          ./autogen.sh
          rm -rf autom4te.cache
          tar -c -z \
              --exclude=".git*" \
              --transform="s,^\.,${ARCHIVE_BASENAME}," \
              -f ~/${ARCHIVE_BASENAME}.tar.gz \
              .
      - uses: actions/upload-artifact@v2
        with:
          name: Source code tarball
          path: ~/${{env.ARCHIVE_BASENAME}}.tar.gz

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    env:
      ARCHIVE_BASENAME: jack1-${{ github.ref_name }}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    needs:
      - archive_source_code
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Source code tarball
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ${{ env.ARCHIVE_BASENAME }}.tar.gz
